idle_bg = "#111111"
idle_fg = "#dcdccc"

good_bg = "#7f9f7f"
good_fg = "#111111"

info_bg = "#6ca0a3"
info_fg = "#111111"

warning_bg = "#f0dfaf"
warning_fg = "#111111"

critical_bg = "#fcace3"
critical_fg = "#111111"

separator = "░"
# separator = "█"
separator_fg = "#ffffff"
separator_bg = "#111111"
