[theme]
name = "moonfly"

[icons]
name = "awesome6"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/grue/mail/dump@dvb.solutions/INBOX", "/home/grue/mail/grigory@tlm.solutions/INBOX" ]
threshold_critical = 1
display_type = "new"
on_click = "foot --app-id floating-foot --window-size-chars=150x50 -- zsh -c neomutt"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/grue/mail/mail@oxapentane.com/INBOX", "/home/grue/mail/mail@oxapentane.com/sinkhole", "/home/grue/mail/grigory@shipunov.xyz/INBOX"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"
on_click = "foot --app-id floating-foot --window-size-chars=150x50 -- zsh -c neomutt"

[[block]]
block = "backlight"
minimum = 5
maximum = 100
cycle = [ 100, 50, 10 ]

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength}"

[[block]]
block = "net"
device = "james"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
format = "{frequency} {barchart} {utilization}"

[[block]]
block = "load"
format = "{1m} {5m} {15m}"

[[block]]
block = "sound"
on_click = "foot --app-id floating-foot -- zsh -c pulsemixer"
headphones_indicator = true

[[block]]
block = "keyboard_layout"
driver = "sway"
format = "{layout}"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
format = "%a %F %R"
