[theme]
theme = "moonfly"

[icons]
icons = "awesome6"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/grue/mail/dump@dvb.solutions/INBOX", "/home/grue/mail/grigory@tlm.solutions/INBOX" ]
threshold_critical = 1
display_type = "new"
[[block.click]]
button = "left"
cmd = "alacritty --class floating-foot -o \"window.dimensions.columns=150\" -o \"window.dimensions.lines=50\" -e zsh -c neomutt"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/grue/mail/mail@oxapentane.com/INBOX", "/home/grue/mail/mail@oxapentane.com/sinkhole", "/home/grue/mail/grigory@shipunov.xyz/INBOX"]
threshold_warning = 1
threshold_critical = 10
display_type = "new"
[[block.click]]
button = "left"
cmd = "alacritty --class floating-foot -o \"window.dimensions.columns=150\" -o \"window.dimensions.lines=50\" -e zsh -c neomutt"

[[block]]
block = "backlight"
minimum = 5
maximum = 100
cycle = [ 100, 50, 10 ]

[[block]]
block = "net"
device = "wlan0"
format = " $icon $ssid $signal_strength "

[[block]]
block = "net"
device = "enp1s0f0"

[[block]]
block = "memory"
format = " $icon $mem_used_percents "

[[block]]
block = "cpu"
format = " $icon $frequency $barchart "#  $utilization"

[[block]]
block = "load"
format = " $1m $5m $15m "

[[block]]
block = "sound"
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "alacritty --class floating-foot -e zsh -c pulsemixer"

[[block]]
block = "keyboard_layout"
driver = "sway"

[[block]]
block = "battery"
driver = "upower"
format = " $icon $percentage $time "
if_command = "test -e /sys/class/power_supply/BAT0"

[[block]]
block = "time"
format = " $icon $timestamp.datetime(f:'%a %F %R', l:nl_NL) "
